[connections.supabase]
SUPABASE_URL = "https://jidpbeybiachjhvcuwpf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZHBiZXliaWFjaGpodmN1d3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTI3NDM0ODUsImV4cCI6MjAyODMxOTQ4NX0.fPE1HtMYpOP3umlwnMbNOtKabsYNcmDsDkbpI7JDOAA"